version: '2'
services:
  v1:
    image: inducosols/r-api-template
    build: ./v1/
    volumes:
     - ./data:/data
     - ./v1:/app
     - ./functions:/functions
    command: /app/plumber.R
    restart: always
    mem_limit: 800m
    env_file: .Renviron
  nginx:
    image: nginx:1.9
    ports:
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
     - v1
